name: atividade_avaliativa
description: "A new Flutter project."

publish_to: 'none'  # Remove isso se quiser publicar no pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'  # Atualizado para faixa compatível com Flutter 3.24+ / Dart 3.5+

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  permission_handler: ^12.0.1
  flutter_sound: ^9.30.0     # Para gravação de áudio
  tflite_flutter: ^0.12.1    # Para rodar o modelo TFLite

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0      # Recomendado para linting

flutter:
  uses-material-design: true

  assets:
    - assets/models/soundclassifier_with_metadata.tflite